### ISSUE TITLE
windows下中文路径问题

### ISSUE THREAD

**Issue by sdzong** [hauter/client#2]
windows下，jar版的放在中文路径下无法启动，执行 `java -jar client.jar` 提示：

> java.io.FileNotFoundException: F:\%e8%b5%84%e6%96%99\client-0.1.2\date.properties (系统找不到指定的路径。)
> 
> > at java.io.FileInputStream.open0(Native Method)
> > at java.io.FileInputStream.open(Unknown Source)
> > at java.io.FileInputStream.<init>(Unknown Source)
> > at java.io.FileInputStream.<init>(Unknown Source)
> > at client.util.PropertyRW.<init>(PropertyRW.java:26)
> > at client.util.PropertyRW.getInstance(PropertyRW.java:43)
> > at client.util.PropertyRW.getInstance(PropertyRW.java:48)
> > at client.view.MainWindow.initComponents(MainWindow.java:146)
> > at client.view.MainWindow.<init>(MainWindow.java:80)
> > at client.view.MainWindow.main(MainWindow.java:466)
> 
> Exception in thread "main" java.lang.NullPointerException
> 
> > at client.util.PropertyRW.<init>(PropertyRW.java:33)
> >        at client.util.PropertyRW.getInstance(PropertyRW.java:43)
> >        at client.util.PropertyRW.getInstance(PropertyRW.java:48)
> >        at client.view.MainWindow.initComponents(MainWindow.java:146)
> >        at client.view.MainWindow.<init>(MainWindow.java:80)
> >        at client.view.MainWindow.main(MainWindow.java:466)

放在全英文路径下没有问题。

exe格式的程序不能在64位jdk下执行，没有测试。

**Comment by hauter** [comment]
中文路径问题的解决方法是在代码中对路径进行编码: URLDecoder；
exe程序是使用exe4j进行打包的，想要使用64位jdk，应该使用exe4j重新打一个64位对于的包。

没空搞这个了，你有兴趣的话可以维护一下。现在感觉这个项目写的很乱。

**Comment by sdzong** [comment]
好的，谢谢您为我们创建了一个这么方便好用的项目
可惜我对java不太了解，虽然有维护的想法，确是心有余而力不足

**Comment by hauter** [comment]
你的联系方式？
